# prefix used in determining full image name in "docker-images" and "compile-docker"
docker-prefix: "wkhtmltopdf/0.12:"

# all targets supported by the docker-related commands, keys are as follows:
#
#   source:         Dockerfile used to build image
#   output:         one of deb, rpm, tar or 7z
#   args:           build-time docker args (optional)
#   arch:           used as arch specified to fpm (for deb or rpm output)
#   matrix:         list of architectures distro supports (NOTE: generates per-arch targets)
#   depend:         dependent packages specified to fpm (for deb or rpm output)
#   qt_config:      override the qt configuration used for building Qt (optional)
#   cross_compile:  use given prefix for cross-compilation (optional)
#   qemu:           emulate via qemu-user-static image for specified platform
#
docker-targets:
  noble:
    source: docker/Dockerfile.debian
    args:
      from: ubuntu:noble
      jpeg: libjpeg-turbo8-dev
      python: python3
    output: deb
    matrix: ['amd64']
    depend: >
      ca-certificates
      fontconfig
      libc6
      libfreetype6
      libjpeg-turbo8
      libpng16-16
      libssl3
      libstdc++6
      libx11-6
      libxcb1
      libxext6
      libxrender1
      xfonts-75dpi
      xfonts-base
      zlib1g

  jammy:
    source: docker/Dockerfile.debian
    args:
      from: ubuntu:jammy
      jpeg: libjpeg-turbo8-dev
      python: python3
    output: deb
    matrix: ['amd64']
    depend: >
      ca-certificates
      fontconfig
      libc6
      libfreetype6
      libjpeg-turbo8
      libpng16-16
      libssl3
      libstdc++6
      libx11-6
      libxcb1
      libxext6
      libxrender1
      xfonts-75dpi
      xfonts-base
      zlib1g

  focal:
    source: docker/Dockerfile.debian
    args:
      from: ubuntu:focal
      jpeg: libjpeg-turbo8-dev
    output: deb
    matrix: ['amd64']
    depend: >
      ca-certificates
      fontconfig
      libc6
      libfreetype6
      libjpeg-turbo8
      libpng16-16
      libssl1.1
      libstdc++6
      libx11-6
      libxcb1
      libxext6
      libxrender1
      xfonts-75dpi
      xfonts-base
      zlib1g

# docker image which provides fpm
fpm-image:      wkhtmltopdf/fpm:1.10.2-20221124

# qemu-user-static -- allow overriding the setup for a specific target
qemu-user-static:
  default:
    image: aptman/qus:d5.0 # chosen because it works with most builds
    setup:
      - "-- -r"
      - "-s -- -p"

# mapping of distro architecture => docker platform
matrix-platforms:
  # debian/ubuntu
  amd64:   linux/amd64
  i386:    linux/386
  armel:   linux/arm/v5
  armhf:   linux/arm/v7
  arm64:   linux/arm64/v8
  ppc64el: linux/ppc64le
  s390x:   linux/s390x
  # centos
  x86_64:  linux/amd64
  i686:    linux/386
  aarch64: linux/arm64/v8
  ppc64le: linux/ppc64le

# parameters for building linux packages via fpm (deb/rpm)
fpm-params:
  name:         wkhtmltox
  description:  convert HTML to PDF and various image formats using QtWebkit
  license:      LGPLv3
  vendor:       wkhtmltopdf
  maintainer:   Ashish Kulkarni <ashish@kulkarni.dev>
  url:          https://wkhtmltopdf.org/
  prefix:       /usr/local
  category:     utils
